/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produto;

import Iva.Iva;
import Words.Words;
import classificacao_produto.ClassificacaoProduto;
import classificacao_produto.ClassificacaoProdutodb;
import currentDateAndTime.CurrentDateAndTime;
import current_user.CurrentUser;
import current_user.CurrentUserdb;
import data.ValidarDataFabricacaoExpiracao;
import fornecedor.Fornecedor;
import fornecedor.Fornecedordb;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import util.NumeroAleatorio;

/**
 *
 * @author vicente
 */
public class ProdutoCadastroForm extends javax.swing.JFrame {

    private Produto produto;
    private ProdutoConnectiondb produtoConnectiondb;
    private Produtodb produtodb;
    private Iva precoProduto;

    private Fornecedordb fornecedordb;
    private ClassificacaoProdutodb classificacaoProdutodb;

    private CurrentUserdb currentUserdb;

    private Words transform;

    private ValidarDataFabricacaoExpiracao data;

    private CurrentDateAndTime time;

    /**
     * Creates new form ProdutoForm
     */
    public ProdutoCadastroForm() {
        super("Cadastro de Produtos");
        initComponents();

        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(salvarJB);
        transform = Words.getInstance();

        time = new CurrentDateAndTime();

        classeProdutoView();
        fornecedorView();
        String codigo = String.valueOf(gerarCodigoProduto());
        codigoProdutoJT.setText(codigo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dataFabricacaoJCA = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        DataExpiracaoJCA = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        codigoProdutoJT = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        nomeProdutoJT = new javax.swing.JTextField();
        nomeFornecedorJC = new javax.swing.JComboBox<>();
        classeProdutoJC = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        quantidadeJT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precoJT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lucroJT = new javax.swing.JTextField();
        salvarJB = new javax.swing.JButton();
        salvarJB1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Data de Fabricação");

        dataFabricacaoJCA.setDateFormatString("yyyy/MM/dd");
        dataFabricacaoJCA.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Data de Expiração");

        DataExpiracaoJCA.setDateFormatString("yyyy/MM/dd");
        DataExpiracaoJCA.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Código do Produto");

        codigoProdutoJT.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        codigoProdutoJT.setText("Código do Produto");
        codigoProdutoJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoProdutoJTMouseClicked(evt);
            }
        });
        codigoProdutoJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoJTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DataExpiracaoJCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoProdutoJT)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 85, Short.MAX_VALUE))
                    .addComponent(dataFabricacaoJCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataFabricacaoJCA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataExpiracaoJCA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoProdutoJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        nomeProdutoJT.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        nomeProdutoJT.setText("Nome do Produto");
        nomeProdutoJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeProdutoJTMouseClicked(evt);
            }
        });
        nomeProdutoJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoJTActionPerformed(evt);
            }
        });

        nomeFornecedorJC.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        nomeFornecedorJC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome do Fornecedor" }));

        classeProdutoJC.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        classeProdutoJC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classe do Produto" }));

        jLabel5.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Nome do Produto");

        quantidadeJT.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        quantidadeJT.setText("Quantidade");
        quantidadeJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantidadeJTMouseClicked(evt);
            }
        });
        quantidadeJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeJTActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Quantidade");

        precoJT.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        precoJT.setText("Preço");
        precoJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precoJTMouseClicked(evt);
            }
        });
        precoJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoJTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Preço");

        jLabel9.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Lucro Unitário");

        lucroJT.setFont(new java.awt.Font("DejaVu Serif", 0, 14)); // NOI18N
        lucroJT.setText("Lucro desse produto");
        lucroJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lucroJTMouseClicked(evt);
            }
        });
        lucroJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lucroJTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classeProdutoJC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeFornecedorJC, 0, 238, Short.MAX_VALUE)
                    .addComponent(nomeProdutoJT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantidadeJT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(precoJT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lucroJT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeProdutoJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeFornecedorJC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classeProdutoJC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lucroJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        salvarJB.setBackground(new java.awt.Color(102, 255, 102));
        salvarJB.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        salvarJB.setForeground(java.awt.Color.black);
        salvarJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-32.png"))); // NOI18N
        salvarJB.setText("Salvar");
        salvarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJBActionPerformed(evt);
            }
        });

        salvarJB1.setBackground(new java.awt.Color(204, 255, 204));
        salvarJB1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        salvarJB1.setForeground(java.awt.Color.black);
        salvarJB1.setText("Visualizar");
        salvarJB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(salvarJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvarJB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarJB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarJB1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precoJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoJTActionPerformed

    private void precoJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precoJTMouseClicked

        precoJT.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_precoJTMouseClicked

    private void quantidadeJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeJTActionPerformed

    private void quantidadeJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantidadeJTMouseClicked

        quantidadeJT.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeJTMouseClicked

    private void nomeProdutoJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoJTActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoJTActionPerformed

    private void nomeProdutoJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeProdutoJTMouseClicked

        nomeProdutoJT.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoJTMouseClicked

    private void salvarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJBActionPerformed

        if (campoNomeMoradaVazioJT()) {

            JOptionPane.showMessageDialog(null, "Os campos de texto Nome do Produto e Endereco não pode estar vazios",
                    "SALVAR FORNECEDOR", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                // Get date from Jcalendar-Chooser
                DateFormat dataF = new SimpleDateFormat("yyyy-MM-dd");
                String dataFabricacao = dataF.format(dataFabricacaoJCA.getDate());

                DateFormat dataE = new SimpleDateFormat("yyyy-MM-dd");
                String dataExpiracao = dataE.format(DataExpiracaoJCA.getDate());

                produtodb = new Produtodb();
                // pesquisar a nome de produto na lista
                String nomeProduto = nomeProdutoJT.getText().toUpperCase();

                // ---------------------------FOREIGN KEY--------------------------- 
                // Get fornecedor ID to save on Produtos
                String nomeFornecedor = nomeFornecedorJC.getSelectedItem().toString();
                fornecedordb = new Fornecedordb();
                int idFornecedor = fornecedordb.getIdClente(nomeFornecedor);

                // Get fornecedor ID to save on Produtos
                classificacaoProdutodb = new ClassificacaoProdutodb();
                String classeProduto = classeProdutoJC.getSelectedItem().toString();
                int idClasseProduto = classificacaoProdutodb.getIdClassificacaoProduto(classeProduto);

                //------------------------------------------------------------------
                String quantidad = quantidadeJT.getText();
                int quantidade = Integer.parseInt(quantidad);

                String prec = precoJT.getText(); // preço em String 

                double preco = Double.parseDouble(prec); // Preço do produto: 1.000.00kz

                produto = new Produto();

                precoProduto = new Iva(preco);

                double iva = precoProduto.getProdutoIva(); // Valor do IVA = 140
                double valorPagarCliente = precoProduto.getNovoPrecoComIva();  // Valor a pagar pelo cliente: 1.140,00kz
                
                // Obter o código do produto do campo de texto
                String codigoProduto = codigoProdutoJT.getText();

                // Validar código do produto
                boolean existe = true;
                
                while (existe){
                    
                    // Verificar se já existe um produto com esse codigo no banco de dados
                    produtodb = new Produtodb();
                    existe = produtodb.getValidarCodigoProduto(codigoProduto);
                    
                    // Se esse codigo não existe então
                    if ( !existe )
                    {
                        // Para o loop
                      break; 
                    }else // se esse codigo existe então
                    {
                        // Gera un novo codigo
                        codigoProduto = gerarCodigoProduto();
                        produtodb = null;
                        continue;
                    }
                }
                
                
                
                time = new CurrentDateAndTime();
                LocalDate dataActual = time.getCurrentDate();

                Double lucro = Double.parseDouble(lucroJT.getText());
                
                LocalDate data_fabricacao = time.toLocalDate( dataFabricacao );
                LocalDate data_expiracao = time.toLocalDate( dataExpiracao );
                
                produto = new Produto(nomeProduto, data_fabricacao, data_expiracao, dataActual,
                        quantidade, codigoProduto, preco, iva, valorPagarCliente, lucro);

                // Definir a classificacao do produdo no cadastro
                produto.setIdClassificacao(idClasseProduto);

                // definir o fornecedor no cadastro
                produto.setFornecedor(new Fornecedor(idFornecedor));

                // Buscar o Usuario corrente fez o login na aplicacão;
                currentUserdb = new CurrentUserdb();
                int idCurrenteUser = currentUserdb.feachIdCurrentUser();
                produto.setCurrentUser(new CurrentUser(idCurrenteUser));

                data = new ValidarDataFabricacaoExpiracao(dataFabricacao, dataExpiracao);

                boolean dataValida = data.getValidacao();

                if (dataValida == true) {
                    // Salvar todos os item no banco de dados
                    produtoConnectiondb = new ProdutoConnectiondb();
                    produtoConnectiondb.salvar(produto);

                } else {
                    JOptionPane.showMessageDialog(null, "A data de expiração deve ser maior que a "
                            + "\ndata de fabricação",
                            "ERRO NA DATA DE FABRIÇÃO E FABRICAÇÃO", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NullPointerException | NumberFormatException e) {

                JOptionPane.showMessageDialog(null, "Possiveis erros:\n"
                        + "1 - Verifica os valores inseridos nos campos numericos\n"
                        + "Quantidade, Preço, Código ;\n"
                        + "2 - Tenha a certeza que os campos de Data de Fabricação\n"
                        + "Data de Expiração não estejam vazios.",
                        "ERRO AO SALVAR O PRODUTO", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_salvarJBActionPerformed

    private void codigoProdutoJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoProdutoJTMouseClicked

        codigoProdutoJT.setText("");
    }//GEN-LAST:event_codigoProdutoJTMouseClicked

    private void codigoProdutoJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoJTActionPerformed

    private void salvarJB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJB1ActionPerformed

        new ProdutoForm().setVisible(true);
    }//GEN-LAST:event_salvarJB1ActionPerformed

    private void lucroJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lucroJTMouseClicked

        lucroJT.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_lucroJTMouseClicked

    private void lucroJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lucroJTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lucroJTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoCadastroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataExpiracaoJCA;
    private javax.swing.JComboBox<Object> classeProdutoJC;
    private javax.swing.JTextField codigoProdutoJT;
    private com.toedter.calendar.JDateChooser dataFabricacaoJCA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lucroJT;
    private javax.swing.JComboBox<Object> nomeFornecedorJC;
    private javax.swing.JTextField nomeProdutoJT;
    private javax.swing.JTextField precoJT;
    private javax.swing.JTextField quantidadeJT;
    private javax.swing.JButton salvarJB;
    private javax.swing.JButton salvarJB1;
    // End of variables declaration//GEN-END:variables

    // Verificar os campos de texto
    private boolean campoNomeMoradaVazioJT() {

        return nomeProdutoJT.getText().isEmpty()
                || "Nome do produto".equals(nomeProdutoJT.getText())
                || quantidadeJT.getText().isEmpty()
                || "Quantidade".equals(quantidadeJT.getText())
                || precoJT.getText().isEmpty()
                || "Preço".equals(precoJT.getText())
                || codigoProdutoJT.getText().isEmpty()
                || "Código do Produto".equals(codigoProdutoJT.getText()); // true
    }

    private boolean todosCamposVazios() {

        return nomeProdutoJT.getText().isEmpty()
                || quantidadeJT.getText().isEmpty()
                //|| dataFabricacaoJT.getText().isEmpty()
                //|| dataExpiracaoJC.getText().isEmpty()
                || quantidadeJT.getText().isEmpty();

    }

    private void classeProdutoView() {

        classificacaoProdutodb = new ClassificacaoProdutodb();

        for (ClassificacaoProduto pro : classificacaoProdutodb.read()) {
            classeProdutoJC.addItem(pro);

        }

    }

    private void fornecedorView() {

        fornecedordb = new Fornecedordb();

        for (Fornecedor forne : fornecedordb.readCombobox()) {
            nomeFornecedorJC.addItem(forne);
        }

    }
    // Gera códigos aleatorios para os produtos que não possuem ids 
    private String gerarCodigoProduto() {

        NumeroAleatorio gerar = null;
        gerar = new NumeroAleatorio(99999999, 1000000000);

        return String.valueOf(gerar.getNumber());
    }

}
