/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classificacao_produto;

import MyInterfaces.ReadDataCombobox1;
import Words.Words;
import javax.swing.JOptionPane;

/**
 *
 * @author vicente
 */
public class ClassificacaoProdutoForm extends javax.swing.JFrame
        implements ReadDataCombobox1 {

    private ClassificacaoProduto classificacaoProduto;
    private ClassificacaoProdutoConnectiondb classificacaoProdutoConnectiondb;
    private ClassificacaoProdutodb classificacaoProdutodb;
    private Words transform;

    /**
     * Creates new form ClassificacaoProdutoForm
     */
    public ClassificacaoProdutoForm() {
        super("Cadastro de Classes de Produtos");
        initComponents();

        this.setLocationRelativeTo(null);
        getRootPane().setDefaultButton(salvarJB);
        transform = Words.getInstance();

        ReadDataCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        salvarJB = new javax.swing.JButton();
        eliminarJB = new javax.swing.JButton();
        actualizarJB = new javax.swing.JButton();
        nomeDaClassJT = new javax.swing.JTextField();
        nomeDeClasseJC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        salvarJB.setBackground(new java.awt.Color(102, 255, 204));
        salvarJB.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        salvarJB.setForeground(new java.awt.Color(0, 0, 0));
        salvarJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-32.png"))); // NOI18N
        salvarJB.setText("Salvar");
        salvarJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJBActionPerformed(evt);
            }
        });

        eliminarJB.setBackground(new java.awt.Color(255, 51, 51));
        eliminarJB.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        eliminarJB.setForeground(new java.awt.Color(0, 0, 0));
        eliminarJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete-black-32.png"))); // NOI18N
        eliminarJB.setText("Eliminar");
        eliminarJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarJBActionPerformed(evt);
            }
        });

        actualizarJB.setBackground(new java.awt.Color(255, 153, 51));
        actualizarJB.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        actualizarJB.setForeground(java.awt.Color.black);
        actualizarJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update-button-32.png"))); // NOI18N
        actualizarJB.setText("Actualizar");
        actualizarJB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizarJB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actualizarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarJBActionPerformed(evt);
            }
        });

        nomeDaClassJT.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        nomeDaClassJT.setForeground(java.awt.Color.black);
        nomeDaClassJT.setText("Nome da Classe");
        nomeDaClassJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomeDaClassJTMouseClicked(evt);
            }
        });
        nomeDaClassJT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDaClassJTActionPerformed(evt);
            }
        });

        nomeDeClasseJC.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        nomeDeClasseJC.setForeground(java.awt.Color.black);
        nomeDeClasseJC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classe do Produto" }));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Classe de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeDeClasseJC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDaClassJT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(actualizarJB, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(salvarJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salvarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarJB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeDaClassJT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomeDeClasseJC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarJBActionPerformed

        if (!itemClasseProdutoSelecionada()) {

            JOptionPane.showMessageDialog(null, "A caixa de Classe de Produto não pode estar vazia \n"
                    + "Seleciona um elemento na caixa de Classe de Produtos",
                    "ELIMINAR CLASSE DE PRODUTO", JOptionPane.ERROR_MESSAGE);

        } else {

            classificacaoProdutoConnectiondb = new ClassificacaoProdutoConnectiondb();

            String nomeClasse = nomeDeClasseJC.getSelectedItem().toString();

            classificacaoProdutoConnectiondb.eliminar(nomeClasse);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarJBActionPerformed

    private void nomeDaClassJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeDaClassJTMouseClicked

        nomeDaClassJT.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDaClassJTMouseClicked

    private void nomeDaClassJTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDaClassJTActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_nomeDaClassJTActionPerformed

    private void salvarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJBActionPerformed

        if (campoNomeDaClasseVazioJT()) {

            JOptionPane.showMessageDialog(null, "O campo de texto não pode estar vazio",
                    "SALVAR CLASSE DE PRODUTO", JOptionPane.ERROR_MESSAGE);

        } else {

             classificacaoProdutodb = new ClassificacaoProdutodb();
            // pesquisar a classe de produto na lista    
            String classeProduto = nomeDaClassJT.getText();
           
             String classe = transform.toUpperCaseAllFirsLetter(classeProduto);

             //verifica se o elemento existe na lista
            boolean existeClassificacao = classificacaoProdutodb.contem(classe);

            
            // verifica se o elemento foi 
            if (existeClassificacao) {
                JOptionPane.showMessageDialog(null, "Essa classificação já existe",
                        "SALVAR CLASSE DE PRODUTO", JOptionPane.ERROR_MESSAGE);
            } else {
                classificacaoProdutoConnectiondb = new ClassificacaoProdutoConnectiondb();


                classificacaoProdutoConnectiondb.salvar(classe);
                nomeDeClasseJC.addItem(classe);

            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_salvarJBActionPerformed

    private void actualizarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarJBActionPerformed

        if (!campoNomeDaClasseVazioJT() && !itemClasseProdutoSelecionada()) {

            JOptionPane.showMessageDialog(null, "O campo de Texto e a caixa de Classe de Produto não pode estar vazia",
                    "ACTUALIZAR CLASSE DE PRODUTO", JOptionPane.ERROR_MESSAGE);

        } else {

            classificacaoProdutoConnectiondb = new ClassificacaoProdutoConnectiondb();

            String novaClasse = nomeDaClassJT.getText();
            String antigaClasse = nomeDeClasseJC.getSelectedItem().toString();

            String novaclass = transform.toUpperCaseAllFirsLetter(novaClasse);

            classificacaoProdutoConnectiondb.actualizar(novaclass, antigaClasse);
            nomeDeClasseJC.addItem(novaClasse);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassificacaoProdutoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassificacaoProdutoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassificacaoProdutoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassificacaoProdutoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassificacaoProdutoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarJB;
    private javax.swing.JButton eliminarJB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeDaClassJT;
    private javax.swing.JComboBox<Object> nomeDeClasseJC;
    private javax.swing.JButton salvarJB;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ReadDataCombobox() {

        classificacaoProdutodb = new ClassificacaoProdutodb();

        for (Object element : classificacaoProdutodb.read()) {

            nomeDeClasseJC.addItem(element);
        }

    }

    private boolean itemClasseProdutoSelecionada() {

        return nomeDeClasseJC.getSelectedIndex() > 0; // true
    }

    private boolean campoNomeDaClasseVazioJT() {

        return nomeDaClassJT.getText().isEmpty() || "Nome da Classe".equals(nomeDaClassJT.getText()); // true
    }

}
